name: Build and Release

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x64, arm64]
        platform: [linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn install
          sudo apt update && sudo apt -y upgrade && sudo apt -y install dpkg fakeroot && sudo apt-get -y install rpm
      - name: Build app ${{ matrix.platform }}_${{ matrix.arch }}
        run: yarn make --arch=${{ matrix.arch }} --platform=${{ matrix.platform }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: ./out/make/*
          draft: true
  build-win32:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [ia32, x64, arm64]
        platform: [win32]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn install
          sudo apt update && sudo apt -y upgrade && sudo apt -y install dpkg fakeroot  && sudo apt-get -y install rpm wine 
          sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get -y install wine32
          sudo apt install ca-certificates gnupg
          sudo gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
          sudo apt update
          sudo apt install -y mono-devel
          sudo mozroots --import --sync
      - name: Build app ${{ matrix.platform }}_${{ matrix.arch }}
        run: yarn make --arch=${{ matrix.arch }} --platform=${{ matrix.platform }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: ./out/make/*
          draft: true
  build-darwin:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        arch: [x64, arm64]
        platform: [darwin]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn install
      - name: Build app ${{ matrix.platform }}_${{ matrix.arch }}
        run: yarn make --arch=${{ matrix.arch }} --platform=${{ matrix.platform }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: ./out/make/*
          draft: true