name: Build and Release

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64, arm64]
        platform: [linux, win32, darwin]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build app ${{ matrix.platform }}_${{ matrix.arch }}
        run: yarn make arch=${{ matrix.arch }} platform=${{ matrix.platform }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: ./out/make/*
          draft: true